[versions]
kotest = "6.1.2"
jvmToolchain = "25"
antlr-kotlin = "1.0.9" # parser generator

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.3.0" }
kotest = { id = "io.kotest", version.ref = "kotest" }
antlr-kotlin = { id = "com.strumenta.antlr-kotlin", version.ref = "antlr-kotlin" }

[libraries]
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlin-kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotlin-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
antlr-kotlin = { module = "com.strumenta:antlr-kotlin-runtime", version.ref = "antlr-kotlin" }
